# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u59d3\u540d'),
        ),
    ]
