# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_registration', '0002_auto_20170428_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u6240\u6709\u7528\u6237\u4fe1\u606f'},
        ),
    ]
