# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_registration', '0003_auto_20170428_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '\u672c\u79d1'), ('2', '\u7855\u58eb'), ('3', '\u535a\u58eb'), ('4', '\u5176\u4ed6')], max_length=128, verbose_name='\u4eba\u5458\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AddField(
            model_name='info',
            name='organization',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u5de5\u4f5c\u5355\u4f4d'),
        ),
        migrations.AddField(
            model_name='info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u59d3\u540d'),
        ),
    ]
