# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_registration', '0004_auto_20170428_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='check_status',
            field=models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (1, '\u901a\u8fc7'), (2, '\u672a\u901a\u8fc7')], default=0, verbose_name='\u5ba1\u6838\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='info',
            name='category',
            field=models.IntegerField(choices=[(1, '\u672c\u79d1'), (2, '\u7855\u58eb'), (3, '\u535a\u58eb'), (0, '\u5176\u4ed6')], default=0, verbose_name='\u4eba\u5458\u7c7b\u522b'),
        ),
    ]
