# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_registration', '0005_auto_20170429_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '\u62a5\u540d\u4fe1\u606f', 'verbose_name_plural': '\u6240\u6709\u62a5\u540d\u4fe1\u606f'},
        ),
    ]
