#!/bin/bash

NAME="GraduateAdmission"
BIND=unix:/tmp/graduate_admission.sock
DJANGO_SETTINGS_MODULE=graduate_admission.settings
DJANGO_WSGI_MODULE=graduate_admission.wsgi
LOG_LEVEL=debug


export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-