#!/bin/bash

NAME="GraduateAdmission"
BIND=unix:graduate_admission.sock
DJANGO_DEBUG=False
DJANGO_SETTINGS_MODULE=graduate_admission.settings
DJANGO_WSGI_MODULE=graduate_admission.wsgi
LOG_LEVEL=debug


export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export DJANGO_DEBUG=False
export DJANGO_WEBSITE='www1.ep.tsinghua.edu.cn:8000'
export DJANGO_YEAR=2019

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
