# Generated by Django 2.0.2 on 2018-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest1',
            field=models.CharField(blank=True, choices=[('核能', '核能方向 - 核能与核技术工程（085226）- 清华本部'), ('核燃料', '核燃料方向（定向） - 核能与核技术工程（085226）- 清华本部'), ('核技术', '核技术方向 - 核能与核技术工程（085226）- 清华本部'), ('公共安全', '公共安全 - 安全工程（085224） - 深圳研究生院'), ('核能安全', '核能安全 - 安全工程（085224） - 深圳研究生院')], max_length=8, null=True, verbose_name='第一志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest2',
            field=models.CharField(blank=True, choices=[('核能', '核能方向 - 核能与核技术工程（085226）- 清华本部'), ('核燃料', '核燃料方向（定向） - 核能与核技术工程（085226）- 清华本部'), ('核技术', '核技术方向 - 核能与核技术工程（085226）- 清华本部'), ('公共安全', '公共安全 - 安全工程（085224） - 深圳研究生院'), ('核能安全', '核能安全 - 安全工程（085224） - 深圳研究生院')], max_length=8, null=True, verbose_name='第二志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest3',
            field=models.CharField(blank=True, choices=[('核能', '核能方向 - 核能与核技术工程（085226）- 清华本部'), ('核燃料', '核燃料方向（定向） - 核能与核技术工程（085226）- 清华本部'), ('核技术', '核技术方向 - 核能与核技术工程（085226）- 清华本部'), ('公共安全', '公共安全 - 安全工程（085224） - 深圳研究生院'), ('核能安全', '核能安全 - 安全工程（085224） - 深圳研究生院')], max_length=8, null=True, verbose_name='第三志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest4',
            field=models.CharField(blank=True, choices=[('核能', '核能方向 - 核能与核技术工程（085226）- 清华本部'), ('核燃料', '核燃料方向（定向） - 核能与核技术工程（085226）- 清华本部'), ('核技术', '核技术方向 - 核能与核技术工程（085226）- 清华本部'), ('公共安全', '公共安全 - 安全工程（085224） - 深圳研究生院'), ('核能安全', '核能安全 - 安全工程（085224） - 深圳研究生院')], max_length=8, null=True, verbose_name='第四志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest5',
            field=models.CharField(blank=True, choices=[('核能', '核能方向 - 核能与核技术工程（085226）- 清华本部'), ('核燃料', '核燃料方向（定向） - 核能与核技术工程（085226）- 清华本部'), ('核技术', '核技术方向 - 核能与核技术工程（085226）- 清华本部'), ('公共安全', '公共安全 - 安全工程（085224） - 深圳研究生院'), ('核能安全', '核能安全 - 安全工程（085224） - 深圳研究生院')], max_length=8, null=True, verbose_name='第五志愿'),
        ),
    ]
