# Generated by Django 2.0.2 on 2018-03-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0002_auto_20180310_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exam_subject',
            field=models.CharField(blank=True, choices=[('安全系统', '安全系统工程'), ('热工', '热工基础'), ('力学', '力学基础'), ('核物理', '核物理'), ('辐射防护', '辐射防护'), ('信号与系统', '信号与系统')], max_length=128, null=True, verbose_name='考试科目'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduate_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='本科毕业时间'),
        ),
    ]
