# Generated by Django 2.0.2 on 2018-03-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0003_auto_20180310_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='files',
            new_name='personal_files',
        ),
    ]
