# Generated by Django 2.0.3 on 2018-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0004_auto_20180310_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check_status',
            field=models.CharField(blank=True, choices=[('未审核', '未审核'), ('通过', '通过'), ('不通过', '不通过')], default='未审核', max_length=128, null=True, verbose_name='审核结果'),
        ),
    ]
