# Generated by Django 2.2.2 on 2020-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0005_profile_check_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exam_for_first_institute',
            field=models.CharField(blank=True, choices=[('否', '不参加'), ('是', '参加')], max_length=128, null=True, verbose_name='是否参加原报考院系复试'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exam_subject',
            field=models.CharField(blank=True, choices=[('安全系统工程', '安全系统工程'), ('热工基础', '热工基础'), ('核燃料循环与材料基础', '核燃料循环与材料基础'), ('核物理', '核物理'), ('辐射防护', '辐射防护'), ('信号与系统', '信号与系统')], max_length=128, null=True, verbose_name='考试科目'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest1',
            field=models.CharField(blank=True, choices=[('能源动力-核能与核技术工程（清华本部）- 核能方向', '能源动力-核能与核技术工程（清华本部）- 核能方向'), ('能源动力-核能与核技术工程（清华本部）-核技术方向', '能源动力-核能与核技术工程（清华本部）-核技术方向'), ('能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目', '能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目'), ('安全科学与技术', '安全科学与技术'), ('资源与环境-安全工程（深研院）-公共安全方向', '资源与环境-安全工程（深研院）-公共安全方向'), ('资源与环境-安全工程（深研院）-核能方向', '资源与环境-安全工程（深研院）-核能方向')], max_length=8, null=True, verbose_name='第一志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest2',
            field=models.CharField(blank=True, choices=[('能源动力-核能与核技术工程（清华本部）- 核能方向', '能源动力-核能与核技术工程（清华本部）- 核能方向'), ('能源动力-核能与核技术工程（清华本部）-核技术方向', '能源动力-核能与核技术工程（清华本部）-核技术方向'), ('能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目', '能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目'), ('安全科学与技术', '安全科学与技术'), ('资源与环境-安全工程（深研院）-公共安全方向', '资源与环境-安全工程（深研院）-公共安全方向'), ('资源与环境-安全工程（深研院）-核能方向', '资源与环境-安全工程（深研院）-核能方向')], max_length=8, null=True, verbose_name='第二志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest3',
            field=models.CharField(blank=True, choices=[('能源动力-核能与核技术工程（清华本部）- 核能方向', '能源动力-核能与核技术工程（清华本部）- 核能方向'), ('能源动力-核能与核技术工程（清华本部）-核技术方向', '能源动力-核能与核技术工程（清华本部）-核技术方向'), ('能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目', '能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目'), ('安全科学与技术', '安全科学与技术'), ('资源与环境-安全工程（深研院）-公共安全方向', '资源与环境-安全工程（深研院）-公共安全方向'), ('资源与环境-安全工程（深研院）-核能方向', '资源与环境-安全工程（深研院）-核能方向')], max_length=8, null=True, verbose_name='第三志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest4',
            field=models.CharField(blank=True, choices=[('能源动力-核能与核技术工程（清华本部）- 核能方向', '能源动力-核能与核技术工程（清华本部）- 核能方向'), ('能源动力-核能与核技术工程（清华本部）-核技术方向', '能源动力-核能与核技术工程（清华本部）-核技术方向'), ('能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目', '能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目'), ('安全科学与技术', '安全科学与技术'), ('资源与环境-安全工程（深研院）-公共安全方向', '资源与环境-安全工程（深研院）-公共安全方向'), ('资源与环境-安全工程（深研院）-核能方向', '资源与环境-安全工程（深研院）-核能方向')], max_length=8, null=True, verbose_name='第四志愿'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest5',
            field=models.CharField(blank=True, choices=[('能源动力-核能与核技术工程（清华本部）- 核能方向', '能源动力-核能与核技术工程（清华本部）- 核能方向'), ('能源动力-核能与核技术工程（清华本部）-核技术方向', '能源动力-核能与核技术工程（清华本部）-核技术方向'), ('能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目', '能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目'), ('安全科学与技术', '安全科学与技术'), ('资源与环境-安全工程（深研院）-公共安全方向', '资源与环境-安全工程（深研院）-公共安全方向'), ('资源与环境-安全工程（深研院）-核能方向', '资源与环境-安全工程（深研院）-核能方向')], max_length=8, null=True, verbose_name='第五志愿'),
        ),
    ]
