# Generated by Django 2.2.2 on 2020-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0006_auto_20200427_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest6',
            field=models.CharField(blank=True, choices=[('能源动力-核能与核技术工程（清华本部）- 核能方向', '能源动力-核能与核技术工程（清华本部）- 核能方向'), ('能源动力-核能与核技术工程（清华本部）-核技术方向', '能源动力-核能与核技术工程（清华本部）-核技术方向'), ('能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目', '能源动力-核能与核技术工程（清华本部）-临床医学交叉人才培养项目'), ('安全科学与技术', '安全科学与技术'), ('资源与环境-安全工程（深研院）-公共安全方向', '资源与环境-安全工程（深研院）-公共安全方向'), ('资源与环境-安全工程（深研院）-核能方向', '资源与环境-安全工程（深研院）-核能方向')], max_length=8, null=True, verbose_name='第六志愿'),
        ),
    ]
