# Generated by Django 2.0.2 on 2018-02-16 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('school', models.CharField(blank=True, max_length=128, null=True, verbose_name='学校')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('W', '女')], max_length=128, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('id_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='身份证号')),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号')),
                ('major_number', models.IntegerField(blank=True, null=True, verbose_name='专业人数')),
                ('major_rank', models.IntegerField(blank=True, null=True, verbose_name='专业排名')),
                ('class_number', models.IntegerField(blank=True, null=True, verbose_name='班级人数')),
                ('class_rank', models.IntegerField(blank=True, null=True, verbose_name='班级排名')),
                ('english_level', models.CharField(blank=True, max_length=128, null=True, verbose_name='英语水平')),
                ('first_degree', models.CharField(blank=True, choices=[('DOC', '博士'), ('MAS', '硕士')], max_length=128, null=True, verbose_name='一志愿学位')),
                ('second_degree', models.CharField(blank=True, choices=[('DOC', '博士'), ('MAS', '硕士')], max_length=128, null=True, verbose_name='二志愿学位')),
                ('first_institution', models.CharField(blank=True, choices=[('DEP', '工物系'), ('INET', '核研院')], max_length=128, null=True, verbose_name='一志愿单位')),
                ('second_institution', models.CharField(blank=True, choices=[('DEP', '工物系'), ('INET', '核研院')], max_length=128, null=True, verbose_name='二志愿单位')),
                ('first_interest', models.CharField(blank=True, choices=[('PPE', '粒子物理实验'), ('PPT', '粒子物理理论'), ('AP', '天体物理'), ('NSE', '核能科学与工程'), ('FSE', '裂变能科学与工程'), ('FPP', '核聚变与等离子物理'), ('NFCM', '核燃料循环与材料'), ('NTA', '核技术及应用'), ('RPEP', '辐射防护及环境保护'), ('MPE', '医学物理与工程'), ('SSE', '安全科学与工程')], max_length=128, null=True, verbose_name='一志愿方向')),
                ('second_interest', models.CharField(blank=True, choices=[('PPE', '粒子物理实验'), ('PPT', '粒子物理理论'), ('AP', '天体物理'), ('NSE', '核能科学与工程'), ('FSE', '裂变能科学与工程'), ('FPP', '核聚变与等离子物理'), ('NFCM', '核燃料循环与材料'), ('NTA', '核技术及应用'), ('RPEP', '辐射防护及环境保护'), ('MPE', '医学物理与工程'), ('SSE', '安全科学与工程')], max_length=128, null=True, verbose_name='二志愿方向')),
                ('fund_applied', models.CharField(blank=True, choices=[('N', '否'), ('Y', '是')], max_length=128, null=True, verbose_name='是否申请资助')),
                ('cloth_size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=128, null=True, verbose_name='服装大小')),
                ('personal_statement', models.FileField(blank=True, null=True, upload_to='upload', verbose_name='个人陈述')),
                ('school_report', models.FileField(blank=True, null=True, upload_to='upload', verbose_name='成绩单')),
                ('other_material', models.FileField(blank=True, null=True, upload_to='upload', verbose_name='其他材料')),
                ('is_confirmed', models.IntegerField(blank=True, default=0, verbose_name='确认提交')),
                ('check_status', models.CharField(blank=True, choices=[('UNCHECKED', '未审核'), ('PASS', '通过'), ('FAIL', '不通过')], default='UNCHECKED', max_length=128, null=True, verbose_name='根管理员初审')),
                ('fund_status', models.CharField(blank=True, choices=[('UNCHECKED', '未审核'), ('PASS', '通过'), ('FAIL', '不通过')], max_length=128, null=True, verbose_name='资助审核结果')),
                ('dep_check_status', models.CharField(blank=True, choices=[('UNCHECKED', '未审核'), ('PASS', '通过'), ('FAIL', '不通过')], default='UNCHECKED', max_length=128, null=True, verbose_name='工物系初审')),
                ('inet_check_status', models.CharField(blank=True, choices=[('UNCHECKED', '未审核'), ('PASS', '通过'), ('FAIL', '不通过')], default='UNCHECKED', max_length=128, null=True, verbose_name='核研院初审')),
                ('dep_retest_grade', models.CharField(blank=True, choices=[('A1', 'A等1'), ('A2', 'A等2'), ('B', 'B等'), ('C', 'C等'), ('UNCHECKED', '未审核')], default='UNCHECKED', max_length=128, null=True, verbose_name='工物系复试结果')),
                ('inet_retest_grade', models.CharField(blank=True, choices=[('A1', 'A等1'), ('A2', 'A等2'), ('B', 'B等'), ('C', 'C等'), ('UNCHECKED', '未审核')], default='UNCHECKED', max_length=128, null=True, verbose_name='核研院复试结果')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '所有用户信息',
            },
        ),
    ]
