# Generated by Django 2.0.2 on 2018-02-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0002_auto_20180217_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_institution',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_institution',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_institute',
            field=models.CharField(blank=True, choices=[('工物系', '工物系'), ('核研院', '核研院')], max_length=128, null=True, verbose_name='一志愿单位'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_institute',
            field=models.CharField(blank=True, choices=[('工物系', '工物系'), ('核研院', '核研院')], max_length=128, null=True, verbose_name='二志愿单位'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check_status',
            field=models.CharField(blank=True, choices=[('未审核', '未审核'), ('通过', '通过'), ('不通过', '不通过')], default='未审核', max_length=128, null=True, verbose_name='根管理员初审'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dep_check_status',
            field=models.CharField(blank=True, choices=[('未审核', '未审核'), ('通过', '通过'), ('不通过', '不通过')], default='未审核', max_length=128, null=True, verbose_name='工物系初审'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dep_retest_grade',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('C', 'C'), ('未审核', '未审核')], default='未审核', max_length=128, null=True, verbose_name='工物系复试结果'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_degree',
            field=models.CharField(blank=True, choices=[('博士', '博士'), ('硕士', '硕士')], max_length=128, null=True, verbose_name='一志愿学位'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_interest',
            field=models.CharField(blank=True, choices=[('粒子物理实验', '粒子物理实验'), ('粒子物理理论', '粒子物理理论'), ('天体物理', '天体物理'), ('核能科学与工程', '核能科学与工程'), ('裂变能科学与工程', '裂变能科学与工程'), ('核聚变与等离子物理', '核聚变与等离子物理'), ('核燃料循环与材料', '核燃料循环与材料'), ('核技术及应用', '核技术及应用'), ('辐射防护及环境保护', '辐射防护及环境保护'), ('医学物理与工程', '医学物理与工程'), ('安全科学与工程', '安全科学与工程')], max_length=128, null=True, verbose_name='一志愿方向'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fund_applied',
            field=models.CharField(blank=True, choices=[('否', '否'), ('是', '是')], max_length=128, null=True, verbose_name='是否申请资助'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fund_status',
            field=models.CharField(blank=True, choices=[('未审核', '未审核'), ('通过', '通过'), ('不通过', '不通过')], max_length=128, null=True, verbose_name='资助审核结果'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=128, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inet_check_status',
            field=models.CharField(blank=True, choices=[('未审核', '未审核'), ('通过', '通过'), ('不通过', '不通过')], default='未审核', max_length=128, null=True, verbose_name='核研院初审'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inet_retest_grade',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B'), ('C', 'C'), ('未审核', '未审核')], default='未审核', max_length=128, null=True, verbose_name='核研院复试结果'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_confirmed',
            field=models.CharField(blank=True, choices=[('否', '否'), ('是', '是')], default='否', max_length=128, verbose_name='确认提交'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_degree',
            field=models.CharField(blank=True, choices=[('博士', '博士'), ('硕士', '硕士')], max_length=128, null=True, verbose_name='二志愿学位'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_interest',
            field=models.CharField(blank=True, choices=[('粒子物理实验', '粒子物理实验'), ('粒子物理理论', '粒子物理理论'), ('天体物理', '天体物理'), ('核能科学与工程', '核能科学与工程'), ('裂变能科学与工程', '裂变能科学与工程'), ('核聚变与等离子物理', '核聚变与等离子物理'), ('核燃料循环与材料', '核燃料循环与材料'), ('核技术及应用', '核技术及应用'), ('辐射防护及环境保护', '辐射防护及环境保护'), ('医学物理与工程', '医学物理与工程'), ('安全科学与工程', '安全科学与工程')], max_length=128, null=True, verbose_name='二志愿方向'),
        ),
    ]
