# Generated by Django 2.0.2 on 2018-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0003_auto_20180218_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '报名信息', 'verbose_name_plural': '所有报名信息'},
        ),
        migrations.AddField(
            model_name='profile',
            name='fund_application_text',
            field=models.TextField(blank=True, null=True, verbose_name='资助申请理由'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_material',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='其他材料'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_statement',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='个人陈述'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_report',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='成绩单'),
        ),
    ]
