# Generated by Django 2.1.7 on 2019-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0005_inetprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inetprofile',
            options={'verbose_name': '报名信息(核研院)', 'verbose_name_plural': '所有报名信息(核研院)'},
        ),
        migrations.AddField(
            model_name='profile',
            name='first_advisor',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='一志愿导师'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_advisor',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='二志愿导师'),
        ),
    ]
