# Generated by Django 2.2.2 on 2020-05-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0006_auto_20190508_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_interest',
            field=models.CharField(blank=True, choices=[('粒子物理与核物理', '粒子物理与核物理'), ('天体物理', '天体物理'), ('核能科学与工程', '核能科学与工程'), ('裂变能科学与工程', '裂变能科学与工程'), ('核聚变与等离子物理', '核聚变与等离子物理'), ('核燃料循环与材料', '核燃料循环与材料'), ('核技术及应用', '核技术及应用'), ('辐射防护及环境保护', '辐射防护及环境保护'), ('医学物理与工程', '医学物理与工程'), ('安全科学与工程', '安全科学与工程')], max_length=128, null=True, verbose_name='一志愿方向'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_interest',
            field=models.CharField(blank=True, choices=[('粒子物理与核物理', '粒子物理与核物理'), ('天体物理', '天体物理'), ('核能科学与工程', '核能科学与工程'), ('裂变能科学与工程', '裂变能科学与工程'), ('核聚变与等离子物理', '核聚变与等离子物理'), ('核燃料循环与材料', '核燃料循环与材料'), ('核技术及应用', '核技术及应用'), ('辐射防护及环境保护', '辐射防护及环境保护'), ('医学物理与工程', '医学物理与工程'), ('安全科学与工程', '安全科学与工程')], max_length=128, null=True, verbose_name='二志愿方向'),
        ),
    ]
