# Generated by Django 2.2.2 on 2020-05-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0007_auto_20200530_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='class_rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fund_application_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fund_applied',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fund_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='admission_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='入学时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='average_score',
            field=models.FloatField(blank=True, null=True, verbose_name='平均成绩'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_major',
            field=models.CharField(blank=True, choices=[('物理学', '物理学'), ('核科学与技术', '核科学与技术'), ('安全科学与工程', '安全科学与工程'), ('材料科学与工程', '材料科学与工程'), ('化学工程与技术', '化学工程与技术'), ('环境科学与工程', '环境科学与工程')], max_length=128, null=True, verbose_name='一志愿专业'),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='毕业时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_major',
            field=models.CharField(blank=True, choices=[('物理学', '物理学'), ('核科学与技术', '核科学与技术'), ('安全科学与工程', '安全科学与工程'), ('材料科学与工程', '材料科学与工程'), ('化学工程与技术', '化学工程与技术'), ('环境科学与工程', '环境科学与工程')], max_length=128, null=True, verbose_name='二志愿专业'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_advisor',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='三志愿导师'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_degree',
            field=models.CharField(blank=True, choices=[('博士', '博士'), ('硕士', '硕士')], max_length=128, null=True, verbose_name='三志愿学位'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_institute',
            field=models.CharField(blank=True, choices=[('工物系', '工物系'), ('核研院', '核研院')], max_length=128, null=True, verbose_name='三志愿单位'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_interest',
            field=models.CharField(blank=True, choices=[('物理学', '物理学'), ('安全科学与工程', '安全科学与工程'), ('裂变能科学与工程', '裂变能科学与工程'), ('核聚变与等离子体物理', '核聚变与等离子体物理'), ('同位素分离、应用与机械', '同位素分离、应用与机械'), ('核技术及应用', '核技术及应用'), ('辐射防护及环境保护', '辐射防护及环境保护'), ('医学物理与工程', '医学物理与工程'), ('材料学', '材料学'), ('化学工程', '化学工程'), ('应用化学', '应用化学'), ('核能科学与工程', '核能科学与工程'), ('核燃料循环与材料', '核燃料循环与材料'), ('环境科学与工程', '环境科学与工程')], max_length=128, null=True, verbose_name='三志愿方向'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_major',
            field=models.CharField(blank=True, choices=[('物理学', '物理学'), ('核科学与技术', '核科学与技术'), ('安全科学与工程', '安全科学与工程'), ('材料科学与工程', '材料科学与工程'), ('化学工程与技术', '化学工程与技术'), ('环境科学与工程', '环境科学与工程')], max_length=128, null=True, verbose_name='三志愿专业'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_interest',
            field=models.CharField(blank=True, choices=[('物理学', '物理学'), ('安全科学与工程', '安全科学与工程'), ('裂变能科学与工程', '裂变能科学与工程'), ('核聚变与等离子体物理', '核聚变与等离子体物理'), ('同位素分离、应用与机械', '同位素分离、应用与机械'), ('核技术及应用', '核技术及应用'), ('辐射防护及环境保护', '辐射防护及环境保护'), ('医学物理与工程', '医学物理与工程'), ('材料学', '材料学'), ('化学工程', '化学工程'), ('应用化学', '应用化学'), ('核能科学与工程', '核能科学与工程'), ('核燃料循环与材料', '核燃料循环与材料'), ('环境科学与工程', '环境科学与工程')], max_length=128, null=True, verbose_name='一志愿方向'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_interest',
            field=models.CharField(blank=True, choices=[('物理学', '物理学'), ('安全科学与工程', '安全科学与工程'), ('裂变能科学与工程', '裂变能科学与工程'), ('核聚变与等离子体物理', '核聚变与等离子体物理'), ('同位素分离、应用与机械', '同位素分离、应用与机械'), ('核技术及应用', '核技术及应用'), ('辐射防护及环境保护', '辐射防护及环境保护'), ('医学物理与工程', '医学物理与工程'), ('材料学', '材料学'), ('化学工程', '化学工程'), ('应用化学', '应用化学'), ('核能科学与工程', '核能科学与工程'), ('核燃料循环与材料', '核燃料循环与材料'), ('环境科学与工程', '环境科学与工程')], max_length=128, null=True, verbose_name='二志愿方向'),
        ),
    ]
