# Generated by Django 2.2.2 on 2020-05-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camper', '0008_auto_20200530_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='average_score',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='平均成绩'),
        ),
    ]
